### ISSUE TITLE
Disable nuisance rules

### ISSUE THREAD

**Issue by joebochill** [pxblue/code-standards#11]
#### Describe the desired behavior
Update rules:
- disable no require imports
- disable no empty functions
- disable strict null checker

#### Describe the current behavior
Rules are currently enabled (or enabled by default)

#### Is this request related to a current issue?
No

#### Additional Context
We've found these rules to be particularly bothersome in a number of projects.

**Comment by emclaug2** [comment]
Not sure what rule the strict null checker is referring to.  Could this be tsconfig setting?

**Comment by joebochill** [comment]
> Not sure what rule the strict null checker is referring to. Could this be tsconfig setting?

I believe so. We can skip this for now unless it comes back up.
