### ISSUE TITLE
Update ESlint Config Rules

### ISSUE THREAD

**Issue by emclaug2** [pxblue/code-standards#22]
#### Describe the desired behavior
Update default eslint rules to be compatible with new versions of @typescript-eslint/parser & @typescript-eslint/eslint-plugin, both versions ^3.0.0.

#### Describe the current behavior
Our rules target the default rules found in version ^2.0.0.
As a result, our pxb-eslint-config is now recommending rules that we no longer have vetted as recommended or use within our own component libraries. 

#### Is this request related to a current issue?
No

**Comment by joebochill** [comment]
can you describe which rules need to be changed, or link out to something with more details?
